### ISSUE TITLE
Adware

### ISSUE THREAD

**Issue by coman49** [soerface/fb-unseen#3]
This Chrome extension has recently started quietly pushing adware in form of popups. Very deceitful. It has already been removed from Chrome store and other sites.

**Comment by soerface** [comment]
The extension was removed from the Chrome Store 4 years ago and was also never published by me on other sites.

**Comment by coman49** [comment]
The spamming extension website which at the bottom links to this page here is - http://fbunseen.com/

**Comment by soerface** [comment]
It clearly states “**Based** on fb-unseen“. They just took the source code from here and modified it to their needs. I'm not affiliated with this site or the entry in the chrome webstore. You may try to leave a review there or report it to google:

Review (probably won't help): https://chrome.google.com/webstore/detail/unseen/iicapmagmhahddefgokbabbgieiogjop/reviews
Report (will help when enough people do it): https://chrome.google.com/webstore/report/iicapmagmhahddefgokbabbgieiogjop
