### ISSUE TITLE
Keeps opening new windows with LAME PORN advertisements.

### ISSUE THREAD

**Issue by amayra** [soerface/fb-unseen#4]
It's a shame, because this used to work really well. Also, before the developer added malware, the extension became really unstable, and made Messenger really glitchy. 
WHY did you destroy such a nice thing ???

**Comment by soerface** [comment]
Same problem with issue #3 - you downloaded an extension from fbunseen.com. It is BASED on the source code I publish here, but I'm not affiliated with this page in any way! Please fill your complain at https://chrome.google.com/webstore/detail/unseen/iicapmagmhahddefgokbabbgieiogjop/reviews, I am not able to do anything about it.
