### ISSUE TITLE
The link to the Chrome extension page is dead, but...

### ISSUE THREAD

**Issue by Auster-South-Anemoi** [soerface/fb-unseen#6]
There's still a Chrome app (https://chrome.google.com/webstore/detail/unseen-for-facebook/jiomcgpfgkeefipihnplhadgdoollmap?utm_source=chrome-ntp-icon) that links to what seems like the author site (https://fbunseen.com/) which links to this Github in the very end of the page.
Is the app in the store legit?

**Comment by soerface** [comment]
I'm not affiliated with the author of this app. However, I took a quick look at the sourcecode of the extension. It is indeed based on my code, and they also made efforts to support blocking on messenger.com.

I can not find anything unusual or malicious in their extension and can therefore recommend it for the time being.
